import artifact from "./plannerDefaults.verified.json"

// plannerDefaults.verified.json is generated by PlannerDefaultsTest in the .NET test
// suite and must not be hand-edited - `dotnet test` rewrites it from OilFieldOptions.
// This module is the only place that knows its shape; everything else imports from here.
//
// The artifact speaks C# vocabulary. The conversions to Vue vocabulary (strategy lists
// to per-strategy booleans, module dictionaries to a name and a count) live on this side
// on purpose, so front-end naming does not leak into the planner library.

export const PLANNER_OPTION_DEFAULTS = artifact.options

export type ElectricPolePreset = {
  width: number
  height: number
  supplyWidth: number
  supplyHeight: number
  wireReach: number
}

export const ELECTRIC_POLE_PRESETS: Record<string, ElectricPolePreset> =
  artifact.electricPolePresets

export const QUALITY_LEVELS: Record<string, number> = artifact.qualityLevels

/** One boolean per strategy: true when the strategy is in the enabled list. */
export function strategyFlags(
  all: readonly string[],
  enabled: readonly string[],
): Record<string, boolean> {
  const flags: Record<string, boolean> = {}
  for (const strategy of all) {
    flags[strategy] = enabled.includes(strategy)
  }
  return flags
}

// The full strategy universes come from the artifact too (options.allPipeStrategies /
// options.allBeaconStrategies), not a hardcoded list here - so a new C# enum member
// shows up automatically instead of silently missing from the Vue defaults.
export const PIPE_STRATEGY_DEFAULTS = strategyFlags(
  artifact.allPipeStrategies,
  artifact.options.pipeStrategies,
)

export const BEACON_STRATEGY_DEFAULTS = strategyFlags(
  artifact.allBeaconStrategies,
  artifact.options.beaconStrategies,
)

/**
 * The C# carries modules as a dictionary of name to count. The UI offers one module
 * and one count, so take the single entry, or nothing when the dictionary is empty.
 */
export function moduleNameAndCount(modules: Record<string, number>): {
  name: string
  count: number
} {
  const entries = Object.entries(modules)
  if (entries.length === 0) {
    return { name: "", count: 0 }
  }
  const [name, count] = entries[0]
  return { name, count }
}

export const PUMPJACK_MODULE_DEFAULT = moduleNameAndCount(artifact.options.pumpjackModules)
export const BEACON_MODULE_DEFAULT = moduleNameAndCount(artifact.options.beaconModules)
