namespace Knapcode.FactorioTools.OilField;

public class ParseBlueprintTest : BaseTest
{
    /// <summary>
    /// Generated by a probe mod running inside Factorio 2.1.14: three pumpjacks, the
    /// second and third mirrored. See CLAUDE.md for the probe-mod technique.
    /// </summary>
    private const string MirroredPumpjacks = "0eNqN0MkKgzAQBuB3mfNQNC5UX6WU4jKUaU0MSSwVybs36qFQK3gaZvm/w0xQdwNpw8pBOQE3vbJQXiawfFdVN89UJQlK0IPUj6p5gkdg1dIbythfEUg5dkxramnGmxpkTSYc4CaNoHsbAr2a7YBEpwxhXGqQWzbUrNvU4wYUB8B4X0SQbEwfIGcG+uMnB3yx659//PAddiSD9n0ywouMXc6zXBRZKtIiifI4Trz/ADGoghU=";

    [Fact]
    public void KeepsTheMirrorFlagOnAFlippedEntity()
    {
        var blueprint = ParseBlueprint.Execute(MirroredPumpjacks);

        Assert.Collection(
            blueprint.Entities,
            e => Assert.Null(e.Mirror),
            e => Assert.True(e.Mirror),
            e => Assert.True(e.Mirror));
    }
}
