using Knapcode.FactorioTools.Data;

namespace Knapcode.FactorioTools.OilField;

public class ParseBlueprintTest : BaseTest
{
    /// <summary>
    /// Generated by a probe mod running inside Factorio 2.1.14: three pumpjacks, the
    /// second and third mirrored. See CLAUDE.md for the probe-mod technique.
    /// </summary>
    private const string MirroredPumpjacks = "0eNqN0MkKgzAQBuB3mfNQNC5UX6WU4jKUaU0MSSwVybs36qFQK3gaZvm/w0xQdwNpw8pBOQE3vbJQXiawfFdVN89UJQlK0IPUj6p5gkdg1dIbythfEUg5dkxramnGmxpkTSYc4CaNoHsbAr2a7YBEpwxhXGqQWzbUrNvU4wYUB8B4X0SQbEwfIGcG+uMnB3yx659//PAddiSD9n0ywouMXc6zXBRZKtIiifI4Trz/ADGoghU=";

    [Fact]
    public void KeepsTheMirrorFlagOnAFlippedEntity()
    {
        var blueprint = ParseBlueprint.Execute(MirroredPumpjacks);

        Assert.Collection(
            blueprint.Entities,
            e => Assert.Null(e.Mirror),
            e => Assert.True(e.Mirror),
            e => Assert.True(e.Mirror));
    }

    private const ulong Version2_1_14 = 562954249306113UL;   // confirmed against a real export
    private const ulong Version1_1_0 = 281479271677952UL;    // FormatVersion(1, 1, 0, 0)

    [Theory]
    // Factorio 2.x blueprints: north omitted, east 4, south 8, west 12.
    [InlineData(0, Version2_1_14, Direction.Up)]
    [InlineData(4, Version2_1_14, Direction.Right)]
    [InlineData(8, Version2_1_14, Direction.Down)]
    [InlineData(12, Version2_1_14, Direction.Left)]
    // An unstamped blueprint is assumed to be modern, because that is what users paste.
    [InlineData(4, 0UL, Direction.Right)]
    // Genuine 1.1 blueprints still parse, when they say so.
    [InlineData(2, Version1_1_0, Direction.Right)]
    [InlineData(6, Version1_1_0, Direction.Left)]
    public void ConvertsBlueprintDirectionsToInternalOnes(int raw, ulong version, Direction expected)
    {
        Assert.Equal(expected, ParseBlueprint.ToInternalDirection((Direction)raw, version));
    }

    /// <summary>
    /// A 2.1.14-stamped blueprint holding one east-facing pumpjack (direction 4) and two rails
    /// at 2.x diagonal directions (2 and 14), which no pumpjack could ever have.
    /// </summary>
    private const string PumpjackWithDiagonalRails = "0eNqN0N0KwiAUB/B3OdcW6j4gXyUi3HZY1nSiLhrDd29zEI110dVRz/F34D9B1Q1onTIBxASq7o0HcZ5PpsEXCEbAq9bIbukaqREE2EHbu6wfQCCMdnlRATXEeCGAJqigcDXSZbyaQVfokrUXbO/nD71Z/HkfPRYExlQjgUY5rNduHskO5B/QBydVewuHuXR7ldGEMro1+Q8z+9vkq8m3JsuXGFIg4itbAk90Pk0UJT8VOc9PGS0Zy2J8A6LMfy4=";

    [Fact]
    public void LeavesTheDirectionOfEntitiesThatAreNotPumpjacksAlone()
    {
        var blueprint = ParseBlueprint.Execute(PumpjackWithDiagonalRails);

        Assert.Collection(
            blueprint.Entities,
            // Converted, because the planner reads this one.
            e =>
            {
                Assert.Equal(EntityNames.Vanilla.Pumpjack, e.Name);
                Assert.Equal(Direction.Right, e.Direction);
            },
            // Untouched. Halving these would reject them, and the blueprint with them.
            e =>
            {
                Assert.Equal("straight-rail", e.Name);
                Assert.Equal(2, (int)e.Direction!.Value);
            },
            e =>
            {
                Assert.Equal("straight-rail", e.Name);
                Assert.Equal(14, (int)e.Direction!.Value);
            });
    }

    [Theory]
    [InlineData(2)]    // northeast in 2.x, not a cardinal
    [InlineData(6)]    // southeast in 2.x, not a cardinal
    [InlineData(10)]   // southwest in 2.x, not a cardinal
    [InlineData(14)]   // northwest in 2.x, not a cardinal
    // Odd values are malformed. Halving them would round down to a cardinal, so a pumpjack
    // would come out silently rotated instead of the blueprint being rejected.
    [InlineData(1)]
    [InlineData(5)]
    [InlineData(9)]
    [InlineData(13)]
    public void RejectsDirectionsAPumpjackCannotHave(int raw)
    {
        var ex = Assert.Throws<FactorioToolsException>(
            () => ParseBlueprint.ToInternalDirection((Direction)raw, Version2_1_14));

        Assert.Contains(raw.ToString(), ex.Message);
    }

    /// <summary>
    /// Exported from Factorio 2.1.14: four pumpjacks facing north, east, south, west.
    /// This is the case the corpus cannot cover, because the corpus is 1.1-encoded.
    /// It is the test that would have caught the original bug report.
    /// </summary>
    private const string FourCardinalPumpjacks = "0eNqN0csKwyAQBdB/mbWU+Eho/JVSSh5Dsa1G1JSG4L/XJIsWkkBWg3rvWTgj1K8erVMmgBxBNZ3xIC8jeHU31Wu6M5VGkGB7bR9V84RIQJkWPyBpvBJAE1RQuLTmw3Azva7RpQBZtQnYzqdCZyY7IdkpJzDMM0ayItgBgv4bBFrlsFmexYbID4hsVzxviOKAyHdFyqZvVAF1An7bIPBG5+dEXrAyF0yUPCso5TF+Abr9jgg=";

    [Fact]
    public void ReadsEveryCardinalFromARealFactorio21Blueprint()
    {
        var blueprint = ParseBlueprint.Execute(FourCardinalPumpjacks);

        Assert.Collection(
            blueprint.Entities,
            // North is written as an omitted field, not as 0, so Direction is always null here.
            // Callers default a null Direction to Up elsewhere (see InitializeContext); this
            // test only pins what the fixture actually contains.
            e => Assert.Null(e.Direction),
            e => Assert.Equal(Direction.Right, e.Direction),
            e => Assert.Equal(Direction.Down, e.Direction),
            e => Assert.Equal(Direction.Left, e.Direction));
    }
}
